# Generated by Django 3.1.3 on 2020-11-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update',
            new_name='updated',
        ),
    ]
